### ISSUE TITLE
cara memakai google-trends-api

### ISSUE THREAD

**Issue by Muqoffin** [azharimm/google-trends-api#1]
hi kak, untuk cara penggunaan API ini gimana ya kak?

**Comment by azharimm** [comment]
Hi, bisa dicek di readme ya

**Comment by Muqoffin** [comment]
hasil statusnya selalu false kak seperti di gambar
![Screenshot_20210711122812](https://user-images.githubusercontent.com/61044238/125183838-b9091b00-e243-11eb-8340-8022dece7d39.png)

**Comment by azharimm** [comment]
semua requestnya POST ya, jadi tidak bisa dari browser seperti itu.
